# Site settings
title: Cyber Defenders
email: cyberdefendersprogram@gmail.com
description:
baseurl: /homepage
url: https://cyberdefenders.github.io/

# Build settings
markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
style: :nested