# Site settings
title: Cyber Defenders
email: cyberdefendersprogram@gmail.com
description: ""
blog: "https://www.medium.com/cyberdefenders"
gitrepo: "https://github.com/cyberdefenders"
shenzibanzaiGitrepo: "https://github.com/cyberdefenders/shenzi-banzai"
secrepoGitrepo: "https://github.com/cyberdefenders/secrepo"
redteamMedium: "https://medium.com/cyberdefenders/red-team-rocks-the-house-d197a9b14540"
baseurl: "/"
url: "https://www.cyberdefendersprogram.com"

# Build settings
markdown: kramdown
permalink: pretty
