# Site settings
title: Cyber Defenders
email: cyberdefendersprogram@gmail.com
description: ""
blog: "https://www.medium.com/cyberdefenders"
gitrepo: "https://github.com/cyberdefenders"
shenzibanzaiGitrepo: "https://github.com/cyberdefenders/shenzi-banzai"
secrepoGitrepo: "https://github.com/cyberdefenders/secrepo"
redteamMedium: "https://medium.com/cyberdefenders/red-team-rocks-the-house-d197a9b14540"
marchHackathon: "https://medium.com/cyberdefenders/our-march-hackathon-in-2-minutes-a64875d37c58"
baseurl: "/"
url: "https://www.cyberdefendersprogram.com"
contact : "_data/contact.html"
advisors: "_data/advisors.html"
partners: "_data/partners.html"

# Build settings
markdown: kramdown
permalink: pretty
