# Site settings
title: Cyber Defenders
email: cyberdefendersprogram@gmail.com
description:
baseurl: "/"
url: "https://www.cyberdefendersprogram.com"

# Build settings
markdown: kramdown
permalink: pretty

port: 3000

# sass:
#   sass_dir: assets/css
# style: :nested
theme: jekyll-theme-minimal