# Site settings
title: Cyber Defenders
email: cyberdefendersprogram@gmail.com
description:
baseurl: "/"
url: "https://www.cyberdefendersprogram.com"

# Build settings
markdown: kramdown
permalink: pretty